version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: myapp-postgres
    restart: always
    ports:
      - "5434:5432"      # host:container
    environment:
      POSTGRES_DB: my_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
